--Part 1
-- id: int
-- employer: varchar(255)
-- name : varchar(255)
-- skills: varchar(255)
--Part 2
-- select name from employer where location = "St. Louis City";
--Part 3
-- drop table job;
--Part 4
-- select * from skill inner join job_skills on job_skills.skills_id = skill.id where job_skills.jobs_id is not null order by name asc;
